"""Tester — stage 4: per-layer test generation + execution.

For each layer in ``ctx["artifacts_by_layer"]`` (the nested per-layer
view the Coder maintains), the Tester:

  1. Asks the LLM to produce a small set of focused test files for the
     layer's purpose + already-generated source files. Output shape is
     ``{path: content}``, parsed via :func:`development._json_utils.parse_llm_json`
     with one strict-temperature retry on garbage.
  2. Detects an appropriate runner via :func:`._runner.detect_runner`
     (pytest for Python, vitest/jest for JS based on package.json,
     shellcheck for shell scripts; ``None`` if no runner is available).
  3. Materializes the layer's source files + the new test files into a
     fresh :class:`._workspace.TestWorkspace` (a temp directory) and
     runs the chosen runner with a hard 30-second timeout.
  4. On ``failed`` or ``errored`` status — and only the *first* time per
     layer per build — invokes the matching layer generator from
     :data:`development.layers.LAYER_GENERATORS` to regenerate the
     LAYER source files (NOT the tests), then re-runs the tests once.
     A second failure is accepted as-is — the loopback is bounded to one
     retry per layer.
  5. Records a per-layer result dict in ``ctx["test_results"]`` and
     publishes a ``STAGE_PROGRESS`` event with the pass/fail counts.

Bounded-loopback contract (orchestrator-visible state):

* ``ctx["_tester_loopbacks"]: set[str]`` — layer names that have
  already been regenerated by the *Tester* this build. SEPARATE from
  ``ctx["_reviewer_loopbacks"]`` (which the Reviewer maintains).
* The Reviewer ran BEFORE the Tester, so a layer may already have been
  regenerated once during review. The Tester's budget is independent —
  a layer may be regenerated up to twice total per build (once by the
  Reviewer, once by the Tester).
* Both sets are pre-seedable by the orchestrator for resume scenarios
  (an already-regenerated layer name in the seed prevents re-regen).

If the test-generation LLM produces unparseable JSON twice in a row,
the layer is recorded with ``status='errored'`` and the build continues
— this stage is best-effort safety, not a hard gate. Other layers are
unaffected.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, ClassVar

from .._json_utils import parse_llm_json
from ..layers import LAYER_GENERATORS
from ..messageboard import MessageBoard
from ..types import STAGE_PROGRESS, LayerGenerationError
from . import _runner as runner_module
from ._workspace import TestWorkspace
from .base import Stage, _chat_or_panel

logger = logging.getLogger("development.stages.tester")


# Pinned so tests can assert byte-for-byte. Kept as a module-level
# constant rather than inlining so prompt experiments are a one-line
# diff.
SYSTEM_PROMPT = (
    "You are a senior test engineer. Given the layer's purpose and the "
    "generated source files, produce a small set of focused tests that "
    "exercise the layer's contract. Output JSON ONLY: "
    "`{file_path: file_content, ...}` mapping test file paths (relative "
    "to the layer dir) to test code. For Python use pytest (no fixtures "
    "unless needed). For JavaScript use vitest if package.json shows it, "
    "else plain assertions. For shell scripts use bats-style or plain "
    "`set -e` checks. Output only valid JSON, no prose."
)

# Strict-retry reminder appended after a parse failure.
RETRY_REMINDER = (
    "Your previous response could not be parsed as JSON. Output ONLY a "
    "valid JSON object whose keys are test file paths and whose values "
    "are the test file contents as strings. No markdown fences, no "
    "commentary."
)


# Hard wall-clock cap on a single runner invocation. Tests that take
# longer than this for a freshly-generated tiny suite are almost
# certainly hung — kill them rather than block the build.
TEST_TIMEOUT_S: float = 30.0


class TesterStage(Stage):
    """Stage 4: per-layer test generation + execution with bounded loopback."""

    name: ClassVar[str] = "tester"
    # Silence pytest's collection-warning heuristic: pytest auto-collects
    # classes whose names start with "Test", and even though we don't
    # actually look like a test class (Stage subclass with __init__),
    # the warning is noisy. This attribute opts out explicitly.
    __test__ = False

    async def run(self, ctx: dict[str, Any]) -> dict[str, Any]:
        artifacts: dict[str, dict[str, str]] = ctx.get("artifacts_by_layer") or {}
        plan: dict[str, Any] = ctx.get("plan") or {}
        board: MessageBoard | None = ctx.get("message_board")

        # Per-build regen tracking. Distinct from Reviewer's
        # `_reviewer_loopbacks` — both stages can each request one
        # regeneration per layer (max 2 per layer per build).
        loopbacks: set[str] = ctx.setdefault("_tester_loopbacks", set())

        test_results: dict[str, dict[str, Any]] = ctx.setdefault("test_results", {})

        if not artifacts:
            # Nothing to test. Leave test_results as-is (empty by
            # default) and return — downstream stages can iterate it
            # without surprise.
            return ctx

        plan_layers = plan.get("layers") or []
        layer_plans = {
            (lp.get("name") or "").lower(): lp
            for lp in plan_layers
            if isinstance(lp, dict)
        }

        # Panel mode/aggregator come from BuildRequest (defaults match
        # the Reviewer's). Last-call telemetry is captured into
        # ``ctx["tester_panel"]`` so observers can inspect the most
        # recent panel consultation; multi-layer builds overwrite the
        # earlier layers' telemetry deliberately — Tester is a per-stage
        # consultation, not a per-layer one.
        request = ctx.get("build_request")
        panel_mode = getattr(request, "panel_mode", None) or "parallel"
        panel_aggregator = (
            getattr(request, "panel_aggregator", None) or "primary-wins"
        )
        last_panel_telemetry: dict[str, Any] | None = None

        for layer_name, files in artifacts.items():
            layer_obj = layer_plans.get(layer_name.lower(), {"name": layer_name})

            # 1. Generate tests. On retry-exhaustion record `errored`
            #    for this layer and move on (other layers continue).
            try:
                tests, telemetry = await self._generate_tests(
                    layer_name, layer_obj, files,
                    mode=panel_mode, aggregator=panel_aggregator,
                )
                if telemetry is not None:
                    last_panel_telemetry = telemetry
            except LayerGenerationError as exc:
                logger.warning(
                    "Tester: layer %r test-generation produced unparseable "
                    "JSON after retry; recording as errored. Issue: %s",
                    layer_name,
                    exc,
                )
                test_results[layer_name] = _errored_result(
                    f"test-generation failed: {exc}"
                )
                self._publish_progress(board, layer_name, test_results[layer_name])
                continue

            # 2-4. Run, possibly regenerate the layer once, run again.
            result = await self._execute_with_loopback(
                layer_name=layer_name,
                layer_obj=layer_obj,
                files=files,
                tests=tests,
                plan=plan,
                artifacts=artifacts,
                loopbacks=loopbacks,
            )

            test_results[layer_name] = result
            self._publish_progress(board, layer_name, result)

        # Re-sync the flat artifacts view if any layer was regenerated.
        # Mirrors what the Reviewer does — the BuildResult serializes
        # the flat view, so it must reflect the post-loopback state.
        if any(name in loopbacks for name in artifacts):
            ctx["artifacts"] = {
                path: content
                for layer_files in artifacts.values()
                for path, content in layer_files.items()
            }
        ctx["test_results"] = test_results
        if last_panel_telemetry is not None:
            ctx["tester_panel"] = last_panel_telemetry
        return ctx

    # ── test generation ─────────────────────────────────────────────

    async def _generate_tests(
        self,
        layer_name: str,
        layer_obj: dict[str, Any],
        files: dict[str, str],
        *,
        mode: str = "parallel",
        aggregator: str = "primary-wins",
    ) -> tuple[dict[str, str], dict[str, Any] | None]:
        """Ask the LLM (or panel) for a {path: content} test-file map.

        Mirrors the layer-generator one-retry pattern: first attempt at
        temp=0.2, retry at temp=0.0 with a strict reminder. Raises
        :class:`LayerGenerationError` on second failure.

        Returns ``(tests, panel_telemetry)``. ``panel_telemetry`` is
        ``None`` when no panel is wired (preserving v2.0 ctx shape).
        """
        user_prompt = _build_user_prompt(layer_name, layer_obj, files)
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]
        raw, telemetry = await _chat_or_panel(
            self._llm, self._reasoning_panel,
            messages, temperature=0.2, max_tokens=4096,
            mode=mode, aggregator=aggregator,
        )
        parsed = parse_llm_json(raw)

        if parsed is None:
            logger.warning(
                "Tester: layer %r test-gen produced unparseable JSON; "
                "retrying once. Raw=%r",
                layer_name,
                raw[:200],
            )
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
                {"role": "assistant", "content": raw},
                {"role": "user", "content": RETRY_REMINDER},
            ]
            raw, telemetry = await _chat_or_panel(
                self._llm, self._reasoning_panel,
                messages, temperature=0.0, max_tokens=4096,
                mode=mode, aggregator=aggregator,
            )
            parsed = parse_llm_json(raw)

        if parsed is None:
            raise LayerGenerationError(layer_name, raw_response=raw)

        # Coerce to {str: str} same way layers/_common does.
        out: dict[str, str] = {}
        for path, content in parsed.items():
            if not isinstance(path, str):
                continue
            if isinstance(content, str):
                out[path] = content
            else:
                out[path] = json.dumps(content, indent=2)
        return out, telemetry

    # ── execution + loopback ────────────────────────────────────────

    async def _execute_with_loopback(
        self,
        *,
        layer_name: str,
        layer_obj: dict[str, Any],
        files: dict[str, str],
        tests: dict[str, str],
        plan: dict[str, Any],
        artifacts: dict[str, dict[str, str]],
        loopbacks: set[str],
    ) -> dict[str, Any]:
        """Run tests; on failure, regenerate the layer once and rerun.

        The regenerate path is gated by ``loopbacks`` — a layer that's
        already in the set (Reviewer doesn't seed this; only the Tester
        does) skips the regen and accepts the first-run result.
        """
        first = await self._run_once(layer_name, files, tests)
        if first["status"] in ("passed", "runner_unavailable", "timeout"):
            # passed — done.
            # runner_unavailable — no runner installed; can't validate,
            #   but a regen wouldn't help. Accept.
            # timeout — could be a hung loop in the gen'd code, but
            #   running the same code again after a regen takes another
            #   30s. The framework calls bounded loopback "best-effort";
            #   we treat timeout as terminal to keep the wall-clock
            #   bounded. (`failed`/`errored` are the loopback triggers.)
            first["regenerated"] = False
            return first

        # status is failed or errored → try one regenerate.
        if layer_name in loopbacks:
            logger.info(
                "Tester: layer %r already regenerated by Tester this build; "
                "accepting %s as-is per bounded-loopback rule.",
                layer_name,
                first["status"],
            )
            first["regenerated"] = False
            return first

        new_files = await self._try_regenerate(
            layer_name, layer_obj, plan, _failure_issues(first)
        )
        if new_files is None:
            first["regenerated"] = False
            return first

        loopbacks.add(layer_name)
        artifacts[layer_name] = new_files

        second = await self._run_once(layer_name, new_files, tests)
        second["regenerated"] = True
        if second["status"] not in ("passed", "runner_unavailable"):
            logger.warning(
                "Tester: layer %r still %s after one regenerate; accepting "
                "as-is per bounded-loopback rule.",
                layer_name,
                second["status"],
            )
        return second

    async def _run_once(
        self,
        layer_name: str,
        files: dict[str, str],
        tests: dict[str, str],
    ) -> dict[str, Any]:
        """Materialize files+tests into a temp workspace and run the runner.

        Workspace is unconditionally torn down (TestWorkspace exits even
        on exceptions). If runner detection returns None we synthesize a
        ``runner_unavailable`` result without spawning anything.
        """
        with TestWorkspace(layer_name, files, tests) as workspace:
            runner = runner_module.detect_runner(workspace, layer_name, {**files, **tests})
            if runner is None:
                return _result_dict(
                    runner_module.RunnerResult(
                        status="runner_unavailable",
                        duration_ms=0,
                        stdout_tail="",
                        stderr_tail="No runner available for this layer.",
                        num_passed=-1,
                        num_failed=-1,
                    ),
                    runner=None,
                )
            res = await runner_module.run_tests(
                workspace, runner, timeout_s=TEST_TIMEOUT_S
            )
            return _result_dict(res, runner=runner)

    async def _try_regenerate(
        self,
        layer_name: str,
        layer_obj: dict[str, Any],
        plan: dict[str, Any],
        issues: list[str],
    ) -> dict[str, str] | None:
        """Invoke the matching layer generator with the failure as feedback.

        Mirrors the Reviewer's signature-tolerant call pattern: try with
        the ``feedback`` kwarg, fall back to no-kwarg for older
        signatures, swallow :class:`LayerGenerationError` and return
        ``None`` so the caller can proceed with the failed result.
        """
        gen = LAYER_GENERATORS.get(layer_name.lower())
        if gen is None:
            logger.info(
                "Tester: no layer generator for %r; skipping loopback.",
                layer_name,
            )
            return None
        try:
            try:
                return await gen(plan, layer_obj, self._llm, feedback=issues)
            except TypeError as exc:
                logger.debug(
                    "Tester: layer generator for %r does not accept "
                    "`feedback` kwarg (%s); calling without it.",
                    layer_name,
                    exc,
                )
                return await gen(plan, layer_obj, self._llm)
        except LayerGenerationError as exc:
            logger.warning(
                "Tester: layer generator for %r raised LayerGenerationError "
                "during loopback: %s. Keeping pre-loopback artifacts.",
                layer_name,
                exc,
            )
            return None

    # ── event publishing ────────────────────────────────────────────

    def _publish_progress(
        self,
        board: MessageBoard | None,
        layer_name: str,
        result: dict[str, Any],
    ) -> None:
        if board is None:
            return
        board.publish(
            STAGE_PROGRESS,
            {
                "stage": self.name,
                "layer": layer_name,
                "status": result.get("status"),
                "num_passed": result.get("num_passed", -1),
                "num_failed": result.get("num_failed", -1),
                "duration_ms": result.get("duration_ms", 0),
                "regenerated": bool(result.get("regenerated", False)),
                "runner": result.get("runner"),
            },
        )


# ── module-level helpers ────────────────────────────────────────────


def _build_user_prompt(
    layer_name: str,
    layer_obj: dict[str, Any],
    files: dict[str, str],
) -> str:
    """Render the test-gen user-message body."""
    purpose = layer_obj.get("purpose") or "(no purpose stated in plan)"
    parts = [
        f"Layer: {layer_name}",
        f"Purpose: {purpose}",
        "",
        "Source files:",
    ]
    for path, content in files.items():
        parts.append(f"--- {path} ---")
        parts.append(content)
    parts.append("")
    parts.append(
        "Generate a small set of focused tests for this layer. "
        "Output JSON only: {test_path: test_content}."
    )
    return "\n".join(parts)


def _result_dict(res: "runner_module.RunnerResult", *, runner: str | None) -> dict[str, Any]:
    """Convert a RunnerResult into a JSON-serializable dict for ctx."""
    return {
        "status": res.status,
        "duration_ms": res.duration_ms,
        "stdout_tail": res.stdout_tail,
        "stderr_tail": res.stderr_tail,
        "num_passed": res.num_passed,
        "num_failed": res.num_failed,
        "runner": runner,
    }


def _errored_result(message: str) -> dict[str, Any]:
    """Synthesize an errored-result dict for cases where we never ran tests."""
    return {
        "status": "errored",
        "duration_ms": 0,
        "stdout_tail": "",
        "stderr_tail": message,
        "num_passed": -1,
        "num_failed": -1,
        "runner": None,
        "regenerated": False,
    }


def _failure_issues(result: dict[str, Any]) -> list[str]:
    """Render the failure tail as a list-of-strings 'issues' for the regen prompt."""
    issues: list[str] = [f"Tests {result.get('status', 'failed')}."]
    nf = result.get("num_failed", -1)
    if nf > 0:
        issues.append(f"{nf} test(s) failed.")
    stderr = result.get("stderr_tail") or ""
    if stderr:
        issues.append(f"stderr: {stderr[-500:]}")
    stdout = result.get("stdout_tail") or ""
    if stdout:
        issues.append(f"stdout: {stdout[-500:]}")
    return issues
