"""Persona Partner (complement_persona) — tests for the round-robin Bravo.

The complementary persona is generated by a SECOND LLM call after the
primary persona, gated by ``opts.persona_mode AND opts.complement_persona``.
On any failure the partner falls back to ``PERSONA_PARTNER_FALLBACK`` and
the primary persona / pipeline is unaffected.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

import pytest

from enhancer.core.events import EventType
from enhancer.core.pipeline import PipelineOptions, run_pipeline
from enhancer.core.transforms import PERSONA_PARTNER_FALLBACK


PASS1_TOKENS = [
    "GOAL: x\n",
    "DOMAIN: y\n",
    "TASK TYPE: analytical\n",
    "AUDIENCE: z\n",
    "IMPLICIT NEEDS: clarity\n",
]
PASS2_TOKENS = [
    "VAGUE TERMS: none\n",
    "MISSING CONTEXT: none\n",
    "UNSTATED CONSTRAINTS: none\n",
    "SCOPE ISSUES: none\n",
    "PRIMARY FOCUS: precision\n",
]
PASS3_TOKENS = ["Enhanced ", "prompt ", "here."]
PASS4_TOKENS = [
    "SPECIFICITY: 8\nCONSTRAINTS: 7\nACTIONABILITY: 9\nIMPROVEMENT: 55\n",
]


@pytest.mark.asyncio
async def test_complement_off_by_default(fake_provider, event_collector):
    """persona_mode=True, complement_persona omitted -> primary persona only."""
    fake_provider.stream_responses.extend([
        PASS1_TOKENS, PASS2_TOKENS,
        ["PERSONA: Senior Architect."],
        PASS3_TOKENS,
        PASS4_TOKENS,
    ])
    on_event, events = event_collector

    result = await run_pipeline(
        "Make me a chatbot.",
        provider=fake_provider, model="fake-7b",
        opts=PipelineOptions(persona_mode=True),
        on_event=on_event,
        request_timeout=10.0, idle_timeout=5.0,
    )

    assert result.persona == "Senior Architect."
    assert result.persona_partner is None

    names = [e[0] for e in events]
    assert EventType.PERSONA_RESULT.value in names
    assert EventType.PERSONA_PARTNER_RESULT.value not in names


@pytest.mark.asyncio
async def test_complement_generates_second_persona(fake_provider, event_collector):
    """Both flags on -> persona AND persona_partner populated, both events fire."""
    fake_provider.stream_responses.extend([
        PASS1_TOKENS, PASS2_TOKENS,
        ["PERSONA: Senior Distributed Systems Architect with 15 years of "
         "experience designing fault-tolerant microservice platforms."],
        ["PERSONA: Site Reliability Engineer with deep expertise in "
         "observability, incident response, and production runbooks."],
        PASS3_TOKENS,
        PASS4_TOKENS,
    ])
    on_event, events = event_collector

    result = await run_pipeline(
        "Make me a chatbot.",
        provider=fake_provider, model="fake-7b",
        opts=PipelineOptions(persona_mode=True, complement_persona=True),
        on_event=on_event,
        request_timeout=10.0, idle_timeout=5.0,
    )

    # Both populated, both non-empty, distinct.
    assert isinstance(result.persona, str) and result.persona
    assert isinstance(result.persona_partner, str) and result.persona_partner
    assert result.persona != result.persona_partner
    assert "Architect" in result.persona
    assert "Reliability" in result.persona_partner

    names = [e[0] for e in events]
    assert EventType.PERSONA_RESULT.value in names
    assert EventType.PERSONA_PARTNER_RESULT.value in names


@pytest.mark.asyncio
async def test_complement_skipped_when_persona_mode_off(
    fake_provider, event_collector,
):
    """complement_persona is a strict child of persona_mode."""
    fake_provider.stream_responses.extend([
        PASS1_TOKENS, PASS2_TOKENS, PASS3_TOKENS, PASS4_TOKENS,
    ])
    on_event, events = event_collector

    result = await run_pipeline(
        "Make me a chatbot.",
        provider=fake_provider, model="fake-7b",
        # persona_mode=False but complement_persona=True
        opts=PipelineOptions(persona_mode=False, complement_persona=True),
        on_event=on_event,
        request_timeout=10.0, idle_timeout=5.0,
    )

    assert result.persona is None
    assert result.persona_partner is None

    names = [e[0] for e in events]
    assert EventType.PERSONA_RESULT.value not in names
    assert EventType.PERSONA_PARTNER_RESULT.value not in names


@pytest.mark.asyncio
async def test_complement_failure_falls_back(fake_provider, event_collector):
    """Partner-LLM raise -> partner falls back, primary persona is unaffected."""
    # Primary persona succeeds; partner stream raises.
    primary_persona = "PERSONA: Senior Distributed Systems Architect."

    # We need to override chat_stream so the FIFTH call (persona partner)
    # raises, while all other calls behave normally. We wrap the existing
    # FakeChatProvider's chat_stream.
    original_chat_stream = fake_provider.chat_stream
    call_count = {"n": 0}

    async def flaky_chat_stream(messages, **kw):  # type: ignore[no-untyped-def]
        call_count["n"] += 1
        if call_count["n"] == 4:
            # Pass1=1, Pass2=2, Persona-A=3, Persona-Partner=4
            async def _gen() -> AsyncIterator[str]:
                if False:
                    yield ""  # noqa: PIE790 — make it an async generator
                raise RuntimeError("partner LLM exploded")
            return _gen()
        return original_chat_stream(messages, **kw)

    # Patch with a sync wrapper: chat_stream returns an async iterator.
    # Replicate the underlying behavior — the source uses `async for tok
    # in provider.chat_stream(...)`, so chat_stream is itself an async
    # generator function. We replicate that contract here.
    async def chat_stream(messages, **kw):  # type: ignore[no-untyped-def]
        call_count["n"] += 1
        # Pass 1, Pass 2, Persona A: succeed. Persona Partner: raise.
        if call_count["n"] == 4:
            raise RuntimeError("partner LLM exploded")
            yield  # noqa — unreachable; makes this an async generator
        # Otherwise delegate to the canned stream_responses queue.
        tokens = (
            fake_provider.stream_responses.pop(0)
            if fake_provider.stream_responses else []
        )
        for tok in tokens:
            yield tok

    fake_provider.chat_stream = chat_stream  # type: ignore[assignment]

    fake_provider.stream_responses.extend([
        PASS1_TOKENS, PASS2_TOKENS,
        [primary_persona],
        # Partner call (4th) raises before consuming a queued response.
        PASS3_TOKENS,
        PASS4_TOKENS,
    ])
    on_event, events = event_collector

    result = await run_pipeline(
        "Make me a chatbot.",
        provider=fake_provider, model="fake-7b",
        opts=PipelineOptions(persona_mode=True, complement_persona=True),
        on_event=on_event,
        request_timeout=10.0, idle_timeout=5.0,
    )

    # Primary persona unaffected.
    assert result.persona == "Senior Distributed Systems Architect."
    # Partner falls back; pipeline did not raise.
    assert result.persona_partner == PERSONA_PARTNER_FALLBACK
    # Pipeline still produced an enhanced result.
    assert result.result == "Enhanced prompt here."

    names = [e[0] for e in events]
    assert EventType.PERSONA_RESULT.value in names
    # Partner event NOT emitted because the call raised before reaching it.
    assert EventType.PERSONA_PARTNER_RESULT.value not in names
