"""Seed the shared services.toml so umbrella components discover each other.

Run once per machine:

    python lab/onboarding.py

Writes (atomically) to `%APPDATA%\\swarm\\services.toml` on Windows or
`~/.config/swarm/services.toml` on Linux/macOS, IFF the file does not
already exist. If it exists, the script prints the current contents and
exits without overwriting.

The schema mirrors what `prompt-enhancer/src/enhancer/api/discovery.py`
and `round-robin/src/round_robin/discovery.py` consume — keep this in
sync with their `DEFAULTS` constants.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from platformdirs import user_config_dir

DEFAULTS = {
    "prompt_enhancer": "http://127.0.0.1:8765",
    "round_robin": "http://127.0.0.1:8766",
    "development": "http://127.0.0.1:8767",
}

_TEMPLATE = """# Shared service discovery for the APL umbrella.
#
# Each component reads this file on startup to look up sibling URLs.
# Defaults below match the components shipped today; remap ports here
# if you run multiple machines on the same LAN.
#
# Generated by lab/onboarding.py — safe to edit by hand.

[services]
{services_block}
"""


def services_path() -> Path:
    return Path(user_config_dir("swarm", appauthor=False)) / "services.toml"


def main() -> int:
    target = services_path()
    if target.exists():
        print(f"services.toml already exists at: {target}")
        print("--- current contents ---")
        print(target.read_text(encoding="utf-8"))
        print("--- (not modified)     ---")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    services_block = "\n".join(
        f'{key} = "{url}"' for key, url in DEFAULTS.items()
    )
    payload = _TEMPLATE.format(services_block=services_block)

    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(payload, encoding="utf-8")
    os.replace(tmp, target)

    print(f"Wrote services.toml at: {target}")
    print("--- contents ---")
    print(payload)
    return 0


if __name__ == "__main__":
    sys.exit(main())
